services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app
    ports:
      - '3000:3000'
    env_file:
      - .env.stage.dev
    volumes:
      - .:/app
    depends_on:
      - db
    command: yarn start:dev

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: nest_management_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
