# ---------- Build stage ----------
FROM node:22 AS builder
WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# ---------- Runtime stage ----------
FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
COPY yarn.lock ./
# Only production deps in final image
RUN yarn install --production --frozen-lockfile --ignore-scripts && yarn cache clean

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/main"]
