# Build
FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build

# Runtime
FROM node:22-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./

RUN yarn install --production

ENV NODE_ENV=production

CMD ["node", "dist/main"]
