name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            APP_DIR=/srv/nestjs-task-management
            CONTAINER=nestjs-app-prod

            # Ensure the repo is present
            if [ ! -d "$APP_DIR/.git" ]; then
              sudo mkdir -p "$APP_DIR"
              sudo chown "$USER":"$USER" "$APP_DIR"
              git clone https://github.com/laura-v-riera/nestjs-task-management.git "$APP_DIR"
            fi

            cd "$APP_DIR"
            git fetch --all
            git reset --hard origin/main

            # Stop and remove current container
            docker rm -f "$CONTAINER" 2>/dev/null || true

            # Build and run fresh
            make prod
