name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            APP_DIR=nestjs-task-management
            CONTAINER=nestjs-app-prod

            cd "$APP_DIR"
            git rev-parse --git-dir || { echo "Not a git repo in $APP_DIR"; exit 1; }

            echo "--- Pulling latest changes ---"
            git fetch --all
            git reset --hard origin/main

            echo "--- Removing old container ---"
            docker rm -f "$CONTAINER" 2>/dev/null || true

            echo "--- Building & running ---"
            make prod
